Cypress.Commands.add('createUserNatura', (firstName, lastName, email, password, cpf, birth, phone) => {
    cy.get('input[name="firstName"]', { timeout : 10000 }).type(firstName)
    cy.get('input[name="lastName"]').type(lastName)
    cy.get('input[name="email"]').type(email)
    cy.get('#password-field').type(password)
    cy.get('#confirmPassword-field').type(password)
    cy.get('input[name="cpf"]').type(cpf)
    cy.get('input[name="dateOfBirth"]').type(birth)
    cy.get('input[value="male"]').click()
    cy.get('input[name="homePhone"]').type(phone)
    cy.get('#acceptedterms').click()
    cy.get('button[type="submit"]').click()
})